name: Bug Report
description: Report a bug or unexpected behaviour in oxidized-skills
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out as many fields below as possible.
        For **security vulnerabilities**, see [SECURITY.md](../../SECURITY.md) — do **not** open a public issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command and full output
      description: The exact command you ran and the complete output (including any error messages).
      render: shell
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Run `oxidized-skills audit ./my-skill`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: check_tools
    attributes:
      label: Output of `oxidized-skills check-tools`
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: oxidized-skills version
      description: Run `oxidized-skills --version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 14.5 / Ubuntu 22.04 / Windows 11"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or log files.
    validations:
      required: false
